-- =============================================================
-- REFEE INITIAL SCHEMA
-- Privacy-first design: legal identity is segregated from public
-- identity at the database level, enforced by RLS.
-- =============================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- =============================================================
-- 1. PUBLIC PROFILES
-- What organizers and other refs can see.
-- First name + last initial only. Never exposes legal name.
-- =============================================================
create table public.public_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null check (length(first_name) between 1 and 50),
  last_initial char(1) not null,
  display_name text generated always as (first_name || ' ' || last_initial || '.') stored,
  city text not null,
  state char(2) not null,
  avatar_url text,
  rating numeric(3,2) default 0.00 check (rating between 0 and 5),
  rating_count integer default 0,
  games_called_total integer default 0,
  show_rate_pct numeric(5,2) default 100.00,
  member_since date default current_date,
  is_active boolean default true,
  is_available boolean default false,
  is_verified boolean default false,
  ref_id_number integer generated by default as identity (start with 10000),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index idx_public_profiles_active on public.public_profiles(is_active) where is_active = true;
create index idx_public_profiles_available on public.public_profiles(is_available) where is_available = true;
create index idx_public_profiles_location on public.public_profiles(state, city);

-- =============================================================
-- 2. PRIVATE PROFILES
-- Sensitive PII. Only readable by the user themselves and admins.
-- Stripe Connect handles SSN — we store reference, not raw value.
-- =============================================================
create table public.private_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legal_first_name text not null,
  legal_last_name text not null,
  date_of_birth date not null,
  phone text not null unique,
  email text,
  -- We never store SSN. Stripe Connect handles tax info.
  stripe_account_id text unique,
  stripe_account_status text default 'pending', -- pending, restricted, complete
  -- Identity verification
  persona_inquiry_id text unique,
  identity_verified_at timestamptz,
  -- Background check
  background_check_provider text default 'ncsi',
  background_check_id text unique,
  background_check_status text default 'pending', -- pending, in_review, cleared, declined
  background_check_completed_at timestamptz,
  background_check_expires_at timestamptz,
  -- Address (for jurisdictional searches)
  street_address text,
  city text,
  state char(2),
  postal_code text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =============================================================
-- 3. SPORTS (sport-agnostic from day one)
-- =============================================================
create table public.sports (
  id text primary key, -- 'basketball', 'soccer', 'football', etc.
  display_name text not null,
  is_active boolean default false,
  launch_order integer
);

-- Seed: basketball is launch sport
insert into public.sports (id, display_name, is_active, launch_order) values
  ('basketball', 'Basketball', true, 1),
  ('soccer', 'Soccer', false, 2),
  ('football', 'Football', false, 3),
  ('volleyball', 'Volleyball', false, 4),
  ('baseball', 'Baseball', false, 5);

-- =============================================================
-- 4. REFEREE SPORTS (which sports a ref officiates)
-- =============================================================
create table public.ref_sports (
  ref_id uuid references public.public_profiles(id) on delete cascade,
  sport_id text references public.sports(id),
  years_experience integer default 0,
  primary key (ref_id, sport_id)
);

-- =============================================================
-- 5. CERTIFICATIONS
-- =============================================================
create table public.certifications (
  id uuid primary key default uuid_generate_v4(),
  ref_id uuid references public.public_profiles(id) on delete cascade,
  org_name text not null, -- 'USAB', 'IAABO', 'NFHS', etc.
  license_number text,
  issued_date date,
  expires_date date,
  is_verified boolean default false,
  document_url text,
  created_at timestamptz default now()
);

-- =============================================================
-- 6. AVAILABILITY PREFERENCES
-- =============================================================
create table public.availability_prefs (
  ref_id uuid primary key references public.public_profiles(id) on delete cascade,
  -- Days of week (0=Sun, 6=Sat) as a bitmask: bit 0 = Sun, bit 6 = Sat
  available_days integer default 0,
  travel_radius_miles integer default 25,
  min_pay_per_game integer default 35,
  min_pay_per_day integer,
  max_games_per_day integer default 6,
  updated_at timestamptz default now()
);

-- =============================================================
-- 7. HIRERS (organizers, leagues, tournament directors)
-- =============================================================
create table public.hirers (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  org_name text not null,
  org_type text not null, -- 'tournament', 'league', 'school', 'parks_rec'
  is_verified boolean default false,
  contact_first_name text,
  contact_last_initial char(1),
  city text,
  state char(2),
  stripe_customer_id text unique,
  created_at timestamptz default now()
);

-- =============================================================
-- 8. JOBS
-- =============================================================
create table public.jobs (
  id uuid primary key default uuid_generate_v4(),
  hirer_id uuid references public.hirers(id) on delete restrict,
  sport_id text references public.sports(id) not null,
  title text not null,
  job_type text default 'single', -- 'single', 'tournament', 'multi_day'
  level text not null, -- 'youth', 'high_school', 'adult', 'pro_am', etc.
  age_group text, -- 'U12', 'U16', 'adult', etc.
  gender text, -- 'boys', 'girls', 'co_ed', 'men', 'women'
  ruleset text, -- 'NFHS', 'FIBA', 'NCAA', etc.
  starts_at timestamptz not null,
  ends_at timestamptz,
  duration_minutes integer,
  -- Location
  venue_name text not null,
  venue_address text,
  venue_city text not null,
  venue_state char(2) not null,
  venue_lat numeric(10,7),
  venue_lng numeric(10,7),
  -- Pay
  pay_per_game integer not null,
  num_games integer default 1,
  pay_total integer generated always as (pay_per_game * num_games) stored,
  payout_window_hours integer default 48,
  -- Crew
  crew_size integer default 2 check (crew_size between 1 and 5),
  -- Status
  status text default 'open', -- 'open', 'partially_filled', 'filled', 'in_progress', 'completed', 'cancelled'
  is_featured boolean default false,
  featured_until timestamptz,
  -- Notes
  hirer_note text,
  uniform_requirements text,
  parking_info text,
  -- Timestamps
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  closes_at timestamptz
);

create index idx_jobs_status_starts_at on public.jobs(status, starts_at);
create index idx_jobs_location on public.jobs(venue_state, venue_city);
create index idx_jobs_featured on public.jobs(is_featured, featured_until) where is_featured = true;

-- =============================================================
-- 9. JOB ASSIGNMENTS (refs assigned to jobs)
-- =============================================================
create table public.job_assignments (
  id uuid primary key default uuid_generate_v4(),
  job_id uuid references public.jobs(id) on delete cascade,
  ref_id uuid references public.public_profiles(id) on delete restrict,
  role text default 'official', -- 'crew_chief', 'official', 'official_2'
  status text default 'pending', -- 'pending', 'accepted', 'declined', 'completed', 'no_show'
  applied_at timestamptz default now(),
  responded_at timestamptz,
  -- Pay tracking
  amount_due integer,
  payout_status text default 'pending', -- 'pending', 'processing', 'paid', 'failed'
  paid_at timestamptz,
  stripe_transfer_id text,
  unique (job_id, ref_id)
);

create index idx_assignments_ref on public.job_assignments(ref_id, status);
create index idx_assignments_job on public.job_assignments(job_id);

-- =============================================================
-- 10. RATINGS (post-game)
-- =============================================================
create table public.ratings (
  id uuid primary key default uuid_generate_v4(),
  job_id uuid references public.jobs(id) on delete cascade,
  ref_id uuid references public.public_profiles(id) on delete cascade,
  hirer_id uuid references public.hirers(id) on delete cascade,
  rating integer check (rating between 1 and 5),
  comment text,
  created_at timestamptz default now(),
  unique (job_id, ref_id, hirer_id)
);

-- =============================================================
-- AUTOMATIC TRIGGERS
-- =============================================================

-- Update timestamps
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_public_profiles_updated_at
  before update on public.public_profiles
  for each row execute function update_updated_at();

create trigger trg_private_profiles_updated_at
  before update on public.private_profiles
  for each row execute function update_updated_at();

create trigger trg_jobs_updated_at
  before update on public.jobs
  for each row execute function update_updated_at();

-- When a rating is added, recompute ref's avg rating
create or replace function recompute_ref_rating()
returns trigger as $$
begin
  update public.public_profiles
  set
    rating = (select avg(rating)::numeric(3,2) from public.ratings where ref_id = new.ref_id),
    rating_count = (select count(*) from public.ratings where ref_id = new.ref_id)
  where id = new.ref_id;
  return new;
end;
$$ language plpgsql security definer;

create trigger trg_recompute_rating
  after insert on public.ratings
  for each row execute function recompute_ref_rating();
